repos:
  - repo: local
    hooks:
      - id: commit-msg-prefix
        name: Commit msg deve iniciar com API-<numero>
        language: system
        entry: sh
        args: ['-c', 'if ! head -1 "$1" | grep -qE "^API-[0-9]+"; then echo "❌ Erro: Commit deve começar com API-XXX (ex: API-81)"; exit 1; fi', '--']
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=88"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
