repos:
  - repo: local
    hooks:
      - id: commit-msg-prefix
        name: Commit msg deve iniciar com API-<numero>
        language: system
        entry: bash -c 'if ! grep -qE "^API-(100|[1-9][0-9]?|[1-9])" "$1"; then echo "Erro-> Commit deve começar com API-XXX (ex-> API-81)"; exit 1; fi'
        args: [".git/commit-msg"]
        stages: [commit-msg]
        pass_filenames: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=88"]

  - repo: https://github.com/pycqa/isort # serve para ordenar imports
    rev: 6.0.1
    hooks:
      - id: isort
