name: CD-Etl

on:
  workflow_run:
    workflows: ["CI-Etl"]
    types:
      - completed
    branches:
      - main

env:
  DOCKERHUB_ENABLED: 'true'
  IMAGE_NAME: inineapi/visiondata-etl
  TAG: ${{ github.sha }}

jobs:
  gather-artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Baixa pacote Python
        uses: actions/download-artifact@v4
        with:
          name: etl-py
          run-id: ${{ github.event.workflow_run.id }}
          path: ./dist

      - name: Baixa cobertura
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          run-id: ${{ github.event.workflow_run.id }}
          path: ./coverage

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: List artifacts
        run: |
          echo "Listing dist:"
          ls -la ./dist || echo "dist not found"
          echo "Listing coverage:"
          ls -la ./coverage || echo "coverage not found"

      - name: Compacta todos (bundle)
        run: |
          mkdir -p bundle
          cp -r dist bundle/ 2>/dev/null || echo "No dist to copy"
          cp -r coverage bundle/ 2>/dev/null || echo "No coverage to copy"
          tar -czf pack-visiondata-etl.tar.gz -C bundle .

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: pack-visiondata-etl
          path: pack-visiondata-etl.tar.gz

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [gather-artifacts]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-visiondata-etl
          path: .

      - name: Extract build artifacts
        run: |
          mkdir -p extracted
          tar -xzf pack-visiondata-etl.tar.gz -C extracted/
          ls -la extracted/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [docker-build-push]
    environment:
      name: staging
    steps:
      - name: Deploy Staging
        run: |
          echo "Deploy Staging with Docker image: ${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "ETL will be available at staging environment"

  deploy-prod:
    runs-on: self-hosted
    needs: [docker-build-push]
    environment:
      name: production
      url: https://visiondata.ininetech.com.br
    steps:
      - name: Deploy Produção via Docker
        run: |
          echo "Deploying Docker image: ${{ env.IMAGE_NAME }}:${{ env.TAG }}"

          # Pull da nova imagem
          docker pull ${{ env.IMAGE_NAME }}:${{ env.TAG }}

          # Parar e remover container antigo
          docker stop visiondata-etl || true
          docker rm visiondata-etl || true

          # Criar diretórios no host se não existirem
          mkdir -p /home/dev/visiondata-etl/logs
          mkdir -p /home/dev/visiondata-etl/data
          mkdir -p /home/dev/visiondata-etl/config

          # Rodar novo container com todas as configurações
          docker run -d \
            --name visiondata-etl \
            --restart unless-stopped \
            --env-file /home/dev/visiondata-etl/.env \
            -v /home/dev/visiondata-etl/logs:/app/logs:rw \
            -v /home/dev/visiondata-etl/data:/app/data:rw \
            -v /home/dev/visiondata-etl/config:/app/config:ro \
            -e PYTHONPATH=/app \
            -e ENVIRONMENT=production \
            -e LOG_DIR=/app/logs \
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

          # Verificar se o container está rodando
          docker ps | grep visiondata-etl
          docker logs visiondata-etl --tail 10

          echo "ETL deploy completed successfully!"
