name: CI-Etl
on:
  pull_request:
    branches:
      - 'API/**'
      - develop
      - 'sprint/**'
      - main
      - prod
    types: [opened, synchronize, reopened]
  push:
    branches:
      - API/**
      - develop
      - sprint/**
      - main
      - prod
permissions:
  contents: read
jobs:
  py-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install deps
        run: |
          pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black ruff pytest build
      - name: Ruff (lint)
        run: ruff check .
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings
      - name: Build (wheel/sdist)
        run: python -m build
      - name: Pacote (tar.gz)
        run: tar -czf etl-py.tar.gz dist/
      - name: Upload artifact (py)
        uses: actions/upload-artifact@v4
        with:
          name: etl-py
          path: etl-py.tar.gz
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
